# Default values for price.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

ingress:
  enabled: false

image:
  repository: 156161676080.dkr.ecr.eu-west-1.amazonaws.com/price
  tag: v2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80